### ISSUE TITLE
message error when installing helpdesk_lite_website

### ISSUE THREAD

**Issue by rrafik** [mustafirus/odoo_addons#1]
Hi

when i install the module a have this message error:

ParseError: "External ID not found in the system: helpdesk_lite.field_helpdesk_ticket_description" while parsing file:///c:/users/rafik/pycharmprojects/odoo-10/extra_addons/helpdesk_lite_website/views/helpdesk_website_data.xml:3, near

< record id="helpdesk_lite.model_helpdesk_ticket" model="ir.model">
            < field name="website_form_default_field_id" ref="helpdesk_lite.field_helpdesk_ticket_description"/>
            < field name="website_form_access">True</field>
            < field name="website_form_label">Create a ticket</field>
        </record >

what can i do to fix ti please.

thank you

**Comment by mustafirus** [comment]
Thank you for request
I know that helpdesk_lite_website have bugs.
I'll fix it in a few days

**Comment by rrafik** [comment]
ok, thank you

**Comment by mustafirus** [comment]
Fixed

**Comment by rrafik** [comment]
Great !  I will test it and give you my feedback

**Comment by mustafirus** [comment]
I'll be very appreciate for your feedback

С ув. А. Голубев
+380(68) 345 2929
+380(50) 353 7155
golubev@nt.net.ua

11.08.2017 16:45, rrafik пишет:

**Comment by rrafik** [comment]
I installed the module and I liked it very much.
The features are simple to use and practical.

I just found an issue when I used the web module in multi-company.
If a user of another company creates a ticket, this ticket is registered under the parent company.

If you like, close this ticket and I will open another with this issue.

In any case thank you for this good module

**Comment by mustafirus** [comment]
Multi-company not tested
open another ticket with this issue plz
