### ISSUE TITLE
Porting to 12.0

### ISSUE THREAD

**Issue by mrddter** [mustafirus/odoo_addons#3]
Hi, have you planned to port helpdesk_lite on 12.0?
If you want I'm available for test it.

**Comment by mustafirus** [comment]
yes... allmost done
in few days i'll post it

**Comment by mrddter** [comment]
Nice, drop me a message here so I can start with tests. 
And .. Happy New Year!!!

**Comment by mrddter** [comment]
hi @mustafirus any news on this?

**Comment by mustafirus** [comment]
published 12.0 port
