### ISSUE TITLE
CE or EE

### ISSUE THREAD

**Issue by eranetsa** [mustafirus/odoo_addons#4]
I installed it to CE but no menu item added to the platform?

**Comment by mrddter** [comment]
I suppose that is ok for CE. Give a look into controllers\portal.py you can found some @route like ex "/my/tickets".

**Comment by gerroon** [comment]
Hi

I think i am having the same issue, I am not a dev, just trying to install an affodrdable helpdesk :(

I am using Odoo 12.0-20190128 (Community Edition) , Docker edition. 

I mounted the addon volume, and i was able to install this addon. But it is nowhere to be seen :( 

Any way to make it visible?

**Comment by BTICOMP** [comment]
Having the same issue installed ok but not showing  on menu

**Comment by mustafirus** [comment]
sorry for timout
to see menus give helpdesk rights to user
